name: My Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t syedahmedimage:${{ github.run_number }} .

      - name: Debug Info
        run: |
          uname -a
          cat /etc/issue
          docker images
          docker ps -a
