name: My Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag syedahmedimage:$(date +%s)

    - name: Release/os of the github action runner
      run: |
       uname-a
       cat /etc/issue
       touch abc.txt

    - name: Build the Docker image
      run: | 
        docker images
        dockere ps -a
